<?php

// @file

function tm_data_tm_api_info() {
  return array(
    'name' => 'TM Static Data',
    'Description' => 'Ticketmaster Static Data',
    'module' => 'tm_data',
    'file' => array('tm_data.inc'),
    'class' => 'tm_data',
    'parameters' => array($acct_id = NULL, $pin = NULL),
  );
}

/**
 * Implementation of hook_flush_caches().
 *
 * This tells Drupal's cache handling system the name of our caching 
 * table, so expired items will be purged automatically and this table 
 * also affected by the empty all caches function.
 */
function tm_data_flush_caches() {
  return array('cache_custom');
}