<?php
// @file
// Calendar list view implementation

/**
 * Implements hook_menu().
 **/
function custom_calendar_menu() {
  $items = array();
  $items['season-schedule'] = array(
    'title' => 'SCHEDULE',
    'page callback' => 'custom_calendar_list_view',
    'access arguments' => array('STH User'),
    'file' => 'custom_calendar.pages.inc',
    'type' => MENU_CALLBACK
  );
  $items['schedule'] = array(
    'title' => 'SCHEDULE',
    'page callback' => 'custom_calendar_list_view',
    'access callback' => TRUE,
    'file' => 'custom_calendar.pages.inc',
    'type' => MENU_CALLBACK
  );
  return $items;
}

/**
 * Implements hook_theme()
 */

function custom_calendar_theme($existing, $type, $theme, $path) {
  return array(
    'list_game_box' => array(
      'arguments' => array(),
      'template' => 'templates/calendar-list-game-box'
    ),
    'calendar_list' => array(
      'arguments' => array(),
      'template' => 'templates/calendar-list-page'
    ),
  );
}