<?php

/**
 * Implements Clear Cache Plugin for Editor User - Ticket STPDEV-773.
 */
function custom_clearcache_menu() {
  $items = array();
  
  $items['admin/manage/clearcache'] = array(
    'title' => 'Clear Cache',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_clearcache_page'),
    'access arguments' => array('administer clearcache settings'),
    'file' => 'custom_clearcache.pages.inc',
   // 'type' => MENU_CALLBACK,
  );

  return $items;
}

/**
 * Implements hook_permission().
 */
function custom_clearcache_permission() {
  return array(
    'administer clearcache settings' => array(
      'title' => t('Administer for clearcache settings'),
      'description' => t('Perform administration tasks for clearcache.'),
    ),
  );
}