/*
 Copyright (c) 2003-2014, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or http://ckeditor.com/license
*/
CKEDITOR.addTemplates("default",{imagesPath:CKEDITOR.getUrl(CKEDITOR.plugins.getPath("templates")+"templates/images/"),templates:[
 {
				title: 'Template with Home, Email, Phone icons',
				image: 'template0.gif',
				description: 'Contact Us - Template with Home, Email, Phone icons to be provided in the editor tool box.',
				html:'<div class="infohourbg"><h4>Hours and Information</h4><div class="row"><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="col-lg-4 col-md-4 col-sm-4 col-xs-4"><div class="fa fa-home fa-3">&nbsp;</div></div><div class="col-lg-8 col-md-8 col-sm-8 col-xs-8"><div class="hour-imf"><div class="hourtp">Office Hours</div><div class="hour-dtl">Monday-Friday<br>9am-5pm</div></div></div></div><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="col-lg-3 col-md-3 col-sm-3 col-xs-3"><div class="fa fa-mobile fa-3">&nbsp;</div></div><div class="col-lg-9 col-md-9 col-sm-9 col-xs-9"><div class="hour-imf"><div class="hourtp">Phone</div><div class="hour-dtl">XXX-XXX-XXXX</div></div></div></div><div class="col-lg-6 col-md-6 col-sm-6 col-xs-6"><div class="col-lg-2 col-md-2 col-sm-2 col-xs-2"><div class="fa fa-envelope-o fa-3">&nbsp;</div></div><div class="col-lg-10 col-md-10 col-sm-10 col-xs-10"><div class="hour-imf"><div class="hourtp">Email</div><div class="hour-dtl"><a href="mailto:xxxxx@io-media.com" class="mail">xxxxx@io-media.com</a></div></div></div></div></div></div>'
 },                                                                                                                           
{title:"Image and Title",image:"template1.gif",description:"One main image with a title and text that surround the image.",html:'<h3><img src=" " alt="" style="margin-right: 10px" height="100" width="100" align="left" />Type the title here</h3><p>Type the text here</p>'},{title:"Strange Template",image:"template2.gif",description:"A template that defines two colums, each one with a title, and some text.",
html:'<table cellspacing="0" cellpadding="0" style="width:100%" border="0"><tr><td style="width:50%"><h3>Title 1</h3></td><td></td><td style="width:50%"><h3>Title 2</h3></td></tr><tr><td>Text 1</td><td></td><td>Text 2</td></tr></table><p>More text goes here.</p>'},{title:"Text and Table",image:"template3.gif",description:"A title with some text and a table.",html:'<div style="width: 80%"><h3>Title goes here</h3><table style="width:150px;float: right" cellspacing="0" cellpadding="0" border="1"><caption style="border:solid 1px black"><strong>Table title</strong></caption><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr><tr><td>&nbsp;</td><td>&nbsp;</td><td>&nbsp;</td></tr></table><p>Type the text here</p></div>'}]});