<?php

/**
 * @file
 * Allows a node content (body) to be broken into multiple pages via any tag.
 *
 * Original module written by Debraj. 
 */

/**
 * Implements hook_menu().
 */
function nodeslider_menu() {
  $items = array();

  $items['admin/config/content/nodeslider'] = array(
    'title' => 'Nodeslider',
    'description' => 'Enable or disable nodeslider, configure separator string, toggle automatic nodeslider and more for each content types.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('nodeslider_settings'),
    'access arguments' => array('administer site configuration'),
    'file' => 'nodeslider.admin.inc',
  );

  return $items;
}

/**
 * Implements hook_node_load().
 */
function nodeslider_node_load($nodes, $types) {
  
    /*$nodeslider_separator = variable_get('nodeslider_separator', '<!--pagebreak-->');
     // Check if manual page separators were used.
	 $body = $node->body;
    if (strpos($body, $nodeslider_separator) !== FALSE) {
      $node->pages = explode($nodeslider_separator, $body);
      $node->page_count = count($node->pages);
    }
	print '<pre>';
	print_r($node->pages); exit;*/
}

/**
 * Implements hook_node_view().
 */
function nodeslider_node_view($node, $view_mode, $langcode) {
  
	    
  if (variable_get('nodeslider_enabled_' . $node->type, 0) == TRUE && $view_mode == 'full') {  
  
    
	$path = drupal_get_path('module','nodeslider');
	
	  
		  $nodeslider_separator = variable_get('nodeslider_separator', '<div style="page-break-after: always"><span style="display: none;">&nbsp;</span></div>');
		 // Check if manual page separators were used.
		 $body = $node->body['und'][0]['value'];
		 $sliderli = '';
		if (strpos($body, $nodeslider_separator) !== FALSE) {
		  $pages = explode($nodeslider_separator, $body);
		  foreach($pages as $val) {
		   $sliderli .= '<li style="width:550px;">'.$val.'</li>';      
		  }
		}
		
		if ($sliderli) {
		$node->content['body']['#prefix'] = '<div class="flexslider-off" id="'.'off-'.$node->nid.'">';
        $node->content['body']['#suffix'] = '</div>';
		
		$flexislider = '<section class="slider">
			<div class="flexslider" id="'.'node-'.$node->nid.'">		
			  <ul class="slides">
				'.$sliderli.'
			  </ul>
			</div>
		  </section>';
		
		  // Add pager to node content.
		  $node->content['nodeslider']['#markup'] = $flexislider;
		   drupal_add_css($path. '/css/flexslider.css');
		   drupal_add_js($path.'/js/jquery.flexslider.js');
	       drupal_add_js($path.'/js/slide.js');
		  }
	 }
      
}