<?php

// @file

/**
 * Implements hook_permission().
 */
function ticketmaster_api_permission() {
  return array(
    'administer ticketmaster api' => array(
      'title' => 'Administer Ticketmaster API Settings'
    ),
  );
}

/**
 * Implements hook_init().
 */
function ticketmaster_api_init() {
  ticketmaster_get_class();
}
/**
 * Implements hook_menu().
 */
function ticketmaster_api_menu() {
  $items = array();
  $items['admin/ticketmaster/api_settings'] = array(
    'title' => 'Ticketmaster API',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('ticketmaster_api_settings_form'),
    'access arguments' => array('administer ticketmaster api'),
    'file' => 'ticketmaster_api.admin.inc',
    'type' => MENU_LOCAL_TASK
  );
  return $items;
}

/**
 * Returns information about the installed ticketmaster apis modules on the system.
 *
 * @return array
 *  An associative array keyed after module name containing information about
 *  the installed apis implementations.
 */
function ticketmaster_get_apis($reset = FALSE) {
  $tm_apis = &drupal_static(__FUNCTION__);
  if (!$tm_apis || $reset) {
    $tm_apis = array();
    foreach (module_implements('tm_api_info') as $module) {
      $tm_apis[$module] = call_user_func($module . '_tm_api_info');
    }
  }
  return $tm_apis;
}

function ticketmaster_get_class() {
  $variable = variable_get('tm_api', 'tm_data');
  $apis = ticketmaster_get_apis();
  if (count($apis)) {
    $tm_api = $apis[$variable];
    if (count($tm_api['file'])) {
      foreach ($tm_api['file'] as $key => $filename) {
        $file = DRUPAL_ROOT . '/' . drupal_get_path('module', $tm_api['module']) . "/$filename";
        if (is_file($file)) {
          $classes[] = require_once $file;
        }
      }
    }
  }
 else {
  return FALSE;
 }
}
