<?php

// @file

/**
 * Implements hook_block_info().
 */
function custom_block_block_info() {
  $blocks = array();
  $blocks['customer_acct_rep_right'] = array(
    'info' => t('Dedicated Experience Managers Right'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['user_info'] = array(
    'info' => t('User Name'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['admin_home_link'] = array(
    'info' => t('Homepage Editor Link'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['countdown_tile'] = array(
    'info' => t('Home page Countdown Tile'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['parking_promo_popup'] = array(
    'info' => t('Logged in Parking Promo Popup'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['promo_tile'] = array(
    'info' => t('Promo Tile'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['main_navigation'] = array(
    'info' => t('Main Navigation'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view()..
 */
function custom_block_block_view($delta) {
  $block = array();
  global $user;
  module_load_include('inc', 'custom_block', 'custom_block.block');
  switch ($delta) {
    case 'customer_acct_rep_right':
      if ($user->uid) {
        $block['subject'] = t('Your') . ' ' . variable_get('subsite_name', '') . ' ' . t('Representative');
        $block['content'] = custom_block_account_rep('block_1');
      }
      return $block;
    case 'user_info':
        $block['subject'] = '';
        $block['content'] = get_user_full_name($user);
      return $block;
    case 'admin_home_link':
        $block['subject'] = '';
        $block['content'] = theme('home_editor_link');
      return $block;
    case 'countdown_tile':
        $block['subject'] = '';
        $block['content'] = custom_block_home_page_countdown_tile();
      return $block;
    case 'parking_promo_popup':
        $block['subject'] = '';
        $block['content'] = custom_block_parking_promo_popup();
      return $block;
    case 'promo_tile':
       $block['subject'] = '';
       $block['content'] = custom_block_promo_tiles();
     return $block;
    case 'main_navigation':
       $block['subject'] = '';
       $block['content'] = custom_block_main_navigation();
     return $block;
  }
}
/**
 * Implements hook_theme()
 */

function custom_block_theme($existing, $type, $theme, $path) {
  return array(
    'home_editor_link' => array(
      'arguments' => array(),
      'template' => 'templates/home-editor-links'
    ),
  );
}
/**
 * function  to replace $ currency format to integer
 */
function get_purchase_price_number($value) {
  $value = str_replace("$", "", $value);
  $value = str_replace(",", "", $value);
  return $value;
}


function invoice_money_format($total) {
  return '$' . number_format((double)$total, 2, '.', ',');
}


function custom_block_get_parent_price_code($seat_holds = array()) {
  if (count($seat_holds)) {
    $seats_info = variable_get('sth_full_season', 'EMAG14FS');
    foreach ($seat_holds as $seats) {
      if (isset($seats->event_name) && $seats->event_name == $seats_info) {
        return $seats->parent_price_code;
      }
    }
  }
  return '';
}