<?php
 /**
 * Preprocessor for theme('event_node_form').
 */
function template_preprocess_event_node_form(&$variables) {    
    $variables['sidebar'] = array();   // Put taxonomy fields in sidebar.    
	$variables['sidebar'][] = $variables['field_event_date'];    
	hide($variables['field_event_date']);
	
    // Extract the form buttons, and put them in independent variable.
	hide($variables['form']['actions']['preview']);
	hide($variables['form']['actions']['delete']);
    $variables['buttons'] = $variables['form']['actions'];	
    hide($variables['form']['actions']);
}

function custom_event_mgmt_overlay_child_initialize() {
  // Add our custom JavaScript.
  drupal_add_js(drupal_get_path('module', 'custom_event_mgmt') . '/overlay-custom-child.js');  
}

/*
 * hook_draggableviews_handler_native_arguments_alter();
 * Purpose: change the weight of any node.
*/
function custom_event_mgmt_draggableviews_handler_native_arguments_alter(&$arguments, $view, &$form_values) {

	if ($form_values){
	 // The transaction opens here.
	  $transaction = db_transaction();
	  try {
	  foreach ($form_values as $val) {  
		$nid = $val['id'];
		$weight = $val['weight'];
		  db_update('weight_weights')
		   ->fields(array(      
		  'weight' => $weight,
		  ))
		  ->condition('entity_id', $nid)
		  ->condition('entity_type', 'node')
		  ->execute();
	   }	  
		  
		  drupal_set_message(t('Sorting updated successfully'));  
	  
	  }
	  catch (Exception $e) {
		$transaction->rollback();	
		drupal_set_message(t('Unable to sort...'));
	  }  
	}
}

/**
 * hook_form_alter().
 * Purpose: need to remove preview button,
 *  need to add back button so, that user can navigation between listing and add or edit node
 **/
function custom_event_mgmt_form_alter(&$form, &$form_state, $form_id){
  /*******************  For ticket STPDEV-309      ****************************/
    $form_type = arg(2);
    $actionString = '';
    $itemType = 'ahref';
    if($form_type == 'edit')
    {
       if (arg(0) == 'node' && is_numeric(arg(1))) 
       {
            $nid = arg(1);
            $node = node_load(array('nid' => $nid));
            $form_type = $node->type;      
        }
    }    
    if($form_type == 'other-event' || $form_type == 'other_event')
    {
        $backtitle = 'Back to 3rd Party Event listing';
        $actionString = 'admin/manage/events/3rd-party-event';
    }else if($form_type == 'games')
    {
        $backtitle = 'Back to Game listing';
        $actionString = 'admin/manage/events';
    }else if($form_type == 'event')
    {
        $backtitle = 'Back to STP Member Event listing';
        $actionString = 'admin/manage/events/sth-event';
    }
    else if($form_type == 'take-over-pages')
    {
        $backtitle = 'Back to Takeover Page listing';
        $actionString = 'admin/manage/take-over-pages';
    }else 
    {
       $backtitle = 'Back';
       $actionString = 'history.go(-1);';
       $itemType = 'button';
    }
    /*******************  End For ticket STPDEV-309      **********************/
  if ($form_id == 'node_delete_confirm'){
    if(isset($form['#node']->title) && $form['#node']->title){
      $form['description']['#markup'] = 'Are you sure you want to delete "' . $form['#node']->title . '"?';
    }  
 }
 
 /*******************  For ticket STPDEV-309      *****************************/
 if(arg(0) == 'node' && (arg(1) == 'add' || arg(2) == 'edit'))
 { 
    $weight = 50; 
    if($itemType == 'ahref')
    { 
      $form['actions']['backtopage'] = array('#type' => 'link',
                                            '#title' => $backtitle,
                                            '#href' => $actionString,
                                            '#options' => array('html' => true,'style'=>'padding-top:5px;padding-bottom:5px'),
                                            '#attributes' => array('class' => array('backtopage'))
                                          );
    }else if($itemType == 'button')
    {
      $form['actions']['backtopage'] = array('#type' => 'button',
                                             '#value' => $backtitle,
                                             '#attributes' => array('class' => array('backtopage'),'onclick'=>$actionString));     
    }
  }
/*******************  End For ticket STPDEV-309      ***************************/
  //remove weight from PDF form  
  if ($form_id == 'quickedit_field_form'){
    unset($form['weight']);  
 }
 if ($form['#form_id'] == 'promo_tile_node_form' && arg(1) == 'add') {
  $arg = arg(3);
   $form['field_user_type']['und']['#default_value'] = $arg;
 }
}