<?php
// @file
/**
 * Implements hook_block_info().
 */
function custom_social_feed_block_info() {
  $blocks = array();
  $blocks['custom_social_feed'] = array(
    'info' => t('Social Feed'),
    'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function custom_social_feed_block_view($delta) {
  $block = array();
  switch ($delta) {
    case 'custom_social_feed':
    module_load_include('inc', 'custom_social_feed', 'custom_social_feed.block');
    $block['subject'] = '';
    $block['content'] = custom_block_social_feed();
      break;
  }
  return $block;
}

/**
 * Implements hook_theme()
 */

function custom_social_feed_theme($existing, $type, $theme, $path) {
  return array(
    'social_feed' => array(
      'variables' => array(),
      'template' => 'templates/social_feed'
    ),
  );
}

function custom_social_feed_menu() {
  $items = array();
   // Social Feed
  $items['admin/manage/settings/social'] = array(
    'title' => 'Social Media',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_social_feed_facebook_pull_settings'),
    'access arguments' => array('administer site settings'),
    'file' => 'custom_social_feed.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  
  $items['admin/manage/settings/social/fb_pull'] = array(
    'title' => 'Facebook',
    'type' => MENU_DEFAULT_LOCAL_TASK,
  );

  $items['admin/manage/settings/social/instagram'] = array(
    'title' => 'Instagram',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_social_feed_instagram_settings'),
    'access arguments' => array('administer site settings'),
    'file' => 'custom_social_feed.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['admin/manage/settings/social/twitter'] = array(
    'title' => 'Twitter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_social_feed_twitter_settings'),
    'access arguments' => array('administer site settings'),
    'file' => 'custom_social_feed.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}


function getInstagramFeeds($url="", $post_data=array(), $is_post = false ){
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_TIMEOUT, 20);
  curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
  if ($is_post){
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, $post_data);
  }
  $feedData = curl_exec($ch);
  curl_close($ch);

  return $feedData;
}

/**
 * Retrieves appropriate tweets (by username, hashkey or search term)
 * and passes over to the theming function with $themekey key passing
 * tweets array along.
 *
 * The rest of this module needs to make sure that corresponding theming
 * functions exist, exist tweets array and perform desired theming.
 *
 * @param $twitkey
 *     Twitter key, which can be a username (prepended with @), hashtag
 *     (prepended with #), or a search term.
 * @param $title
 *     Title passed to the theme template.
 * @param $num_items
 *     Number of tweets to retrieve from Twitter. Can't be more than 200.
 * @param $themekey
 *     Theme key name to use for theming the output of Twitter API.
 * @param $lazy_load
 *     Use javascript to retrieve the twitter results once the page is loaded.
 */
function custom_social_twitter_pull_render($twitkey, $title = NULL, $num_items = NULL, $themekey = NULL, $lazy_load = FALSE) {
  drupal_add_css(drupal_get_path('module', 'twitter_pull') . '/twitter-pull-listing.css');
  $tweets = array();
  //-- Set the lazy load id. Encode the twitkey and title to make sure the they don't contain dashes.
  $lazy_id = rtrim(base64_encode($twitkey) .'-'. base64_encode($title) .'-'. (int)$num_items . '-' . $themekey, '-');

  //-- Set defaults if empty arguments were passed
  $title = (empty($title) && $title != FALSE ) ? t('Related Tweets') : $title;
  $themekey = empty($themekey) ? 'twitter_pull_listing' : $themekey;
  $num_items = empty($num_items) ? twitter_pull_num_items() : $num_items;
  $tweets = twitter_pull_retrieve($twitkey, $num_items);
  return count($tweets) ? $tweets : array();
}

/**
 * function to fetch FB feed
 */
function custom_social_fb_feed($url){
  $ch = curl_init();
  curl_setopt($ch, CURLOPT_URL, $url);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
  curl_setopt($ch, CURLOPT_TIMEOUT, 20);
  curl_setopt($ch,CURLOPT_SSL_VERIFYPEER,false);
  $feedData = curl_exec($ch);
  curl_close($ch);
  return $feedData;
}