<?php
/**
 * Implements hook_menu().
 */
function custom_manage_pages_menu() {
  $items = array();
  //admin/manage/
  $items['admin/manage/manage-pages'] = array(
    'title' => 'Manage Pages',
    'description' => 'Manage Pages',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_manage_pages_callback'),
    'access callback' => 'custom_manage_pages_permission_check',
    'file' => 'custom_manage_pages.pages.inc',
    'type' => MENU_NORMAL_ITEM
  );
  $items['admin/manage/delete-pages/%'] = array(
    'title' => 'Delete Page',
    'page callback' => 'delete_manage_pages',
    'page arguments' => array(3),
    'access callback' => 'custom_manage_pages_permission_check',
    'file' => 'custom_manage_pages.pages.inc',
    'type' => MENU_CALLBACK
  );/**/
  return $items;
}

function custom_manage_pages_permission_check(){
  return TRUE;
}