<?php
/**
 * Implements hook_menu().
 */
function custom_renew_menu() {
  $items = array();
  $items['admin/manage/settings/renew'] = array(
    'title' => 'renew Settings',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('custom_renew_setting'),
    'access arguments' => array('administer site settings'),
    'file' => 'custom_renew.admin.inc',
    'type' => MENU_LOCAL_TASK,
  );
  $items['goto-renew'] = array(
    'title' => 'Renew',
    'page callback' => 'custom_renew_page',
    'access arguments' => array('STH User'),
    'file' => 'custom_renew.inc',
    'type' => MENU_CALLBACK,
  );
  return $items;
}
/**
 * Implements hook_theme()
 */

function custom_renew_theme($existing, $type, $theme, $path) {
  return array(
    'renew' => array(
      'arguments' => array('name' => NULL, 'acct_id' => NULL),
      'template' => 'templates/custom_renew'
    )
  );
}

function _renew_status_table($data) {
  if(count($data)<=0){
    return;
  }
  global $user;
  db_insert('tbl_renew_takeover')
  ->fields(array(
    'acct_id' => (isset($data['acct_id']) && $data['acct_id']) ? $data['acct_id'] : '',
    'show_popup' => (isset($data['show_popup']) && $data['show_popup']) ? $data['show_popup'] : 0)
    )->execute();
}